### ISSUE TITLE
Responsive round images for authors in Blog section

### ISSUE THREAD

**Issue by TheGameFreak720** [TheGameFreak720/CommitHub-Blog#33]
# Background

In the blog section of the website, we have 2 instances where we show the image of the author who wrote the blog post.  One of the previews of the blogs card and one when you click the blog card. They look pretty good round but depending on the width of the device they will stretch badly or have a bad height. 

# Technical Description

The only image right now used is this one https://commithub.s3.us-east-2.amazonaws.com/blog-posts/author/luis.jpg. You can find it getting imported in each blog post markdown file. It may require resizing the image to different heights and widths depending on the device. If you do resizes please include the images in a new folder inside images called the author and I will upload them to s3 and include the links myself.

Files you will be working on are

* src/components/BlogCard.js
* src/components/styles/blog-card.scss
* src/templates/post.js
* src/templates/styles/post.scss

**Comment by erinesullivan** [comment]
I'm ready to create two pull requests for you. :grinning:

**Comment by TheGameFreak720** [comment]
@erinesullivan Make sure to pull develop and make a pull for that branch

**Comment by TheGameFreak720** [comment]
This [issue](https://github.com/TheGameFreak720/CommitHub-Blog/pull/48) was merged in today and it's good to be closed
